### ISSUE TITLE
informações laterais do projeto

### ISSUE THREAD

**Issue by danroxha** [DavidGomesh/info-group-si#1]
# Detalhes do projeto
- Adiciona na lateral algumas ***keywords*** (html, js, ifma, horario) e outras que você achar interessante
- O link direto para o site ***[https://davidgomesh.github.io/info-group-si/](https://davidgomesh.github.io/info-group-si/)***
![Screenshot from 2021-01-12 21-27-28](https://user-images.githubusercontent.com/38236602/104391430-9d37ed00-551e-11eb-959d-12f9ce109c16.jpg)

**Comment by DavidGomesh** [comment]
> # Detalhes do projeto
> - Adiciona na lateral algumas ***keywords*** (html, js, ifma, horario) e outras que você achar interessante
> - O link direto para o site ***[https://davidgomesh.github.io/info-group-si/](https://davidgomesh.github.io/info-group-si/)***
> ![Screenshot from 2021-01-12 21-27-28](https://user-images.githubusercontent.com/38236602/104391430-9d37ed00-551e-11eb-959d-12f9ce109c16.jpg)
> 

Boa! Como faz isso mano?

**Comment by danroxha** [comment]
> > # Detalhes do projeto
> > 
> > * Adiciona na lateral algumas _**keywords**_ (html, js, ifma, horario) e outras que você achar interessante
> > * O link direto para o site _**https://davidgomesh.github.io/info-group-si/**_
> >   ![Screenshot from 2021-01-12 21-27-28](https://user-images.githubusercontent.com/38236602/104391430-9d37ed00-551e-11eb-959d-12f9ce109c16.jpg)
> 
> Boa! Como faz isso mano?

No teu projeto,vai aparecer uma engrenagem eh so clicar e editar. As informacoes adicionadas nela, ajuda o teu projeto  a ser encontrado no mecanismo de busca do github

**Comment by DavidGomesh** [comment]
Beleza, fiz isso! Vou usar essa dica nos outros repositório também! Obrigado! ^-^
